intro: ""
title: "CanadaWildFireDaily: A Large-scale Dataset for Daily Wildfire Spread in Canada"
description:
  - Conference on Neural Information Processing Systems (NeurIPS) 2023, Datasets and Benchmarks track.
  - An earlier version of this work, "Bird Distribution Modelling using Remote Sensing and Citizen Science Data" was presented as a contributed talk at ICLR 2023 Tackling Climate Change with Machine Learning workshop.
buttons:
  SatBird Dataset: https://huggingface.co/datasets/CanadaWildFireDaily/CanadaWildFireDaily-v1
  Paper: ""
  Datasheet: ""
  Code: "https://anonymous.4open.science/r/CanadaWildFireDaily-5819/README.md"
  Talk: ""
  Poster: ""
  Authors: "#authors"
