intro: ""
title: "CanadaWildfireDaily: A Dataset and Benchmark for Daily Wildfire Spread in Canada"
description:
  - Currently Under Review
buttons:
  CanadaWildFireDaily Dataset: https://huggingface.co/datasets/CanadaWildFireDaily/CanadaWildFireDaily-v1
  Paper: ""
  Datasheet: ""
  Code: "https://github.com/hagerradi/CanadaWildFireDaily"
  Talk: ""
  Poster: ""
  Authors: "#authors"
